CREATE TABLE IF NOT EXISTS student_learning_goals (
    student_id INT NOT NULL PRIMARY KEY,
    target_mastery TINYINT UNSIGNED NOT NULL DEFAULT 70,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_learning_goal_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
